x=y=p=q=0
b=d=1
a=10
require('fs').readFileSync(process.argv[2],{encoding:`utf8`}).trim().split`
`.map(l=>{U=(u=+l.slice(1))/90
c=l[0]
y+=Y=u*(c==`N`)-u*(c==`S`)
b+=Y
x+=X=u*(c==`E`)-u*(c==`W`)
a+=X
if(L=c==`L`)d=(d+8-U)%4
if(R=c==`R`)d=(d+U)%4
if(L&U==1|R&U==3)[a,b]=[-b,a]
if(L&U==3|R&U==1)[a,b]=[b,-a]
if((L|R)&U==2)[a,b]=[-a,-b]
if(c==`F`){p+=a*u,q+=b*u
y+=u*!d-u*(d==2)
x+=u*(d==1)-u*(d==3)}})
console.log((A=Math.abs)(x)+A(y),A(p)+A(q))